[project]
name = "plannificationdumanger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.119.0",
    "pandas>=2.3.3",
    "pydantic>=2.12.0",
    "pydantic-mongo>=3.1.0",
    "streamlit>=1.50.0",
]
